// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Modelo;

#nullable disable

namespace Modelo.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20250729054644_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.0");

            modelBuilder.Entity("ConsumoDescuento", b =>
                {
                    b.Property<int>("ConsumoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DescuentosAplicadosDescuentoId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ConsumoId", "DescuentosAplicadosDescuentoId");

                    b.HasIndex("DescuentosAplicadosDescuentoId");

                    b.ToTable("ConsumoDescuento");
                });

            modelBuilder.Entity("Entidades.Acreditacion", b =>
                {
                    b.Property<int>("AcreditacionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<string>("MedioDePago")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Monto")
                        .HasColumnType("TEXT");

                    b.Property<int?>("TarjetaCreditoTarjetaId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TarjetaId")
                        .HasColumnType("INTEGER");

                    b.HasKey("AcreditacionId");

                    b.HasIndex("TarjetaCreditoTarjetaId");

                    b.HasIndex("TarjetaId");

                    b.ToTable("Acreditaciones");
                });

            modelBuilder.Entity("Entidades.Consumo", b =>
                {
                    b.Property<int>("ConsumoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Comercio")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool?>("EsRecurrente")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<string>("Hora")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Moneda")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Monto")
                        .HasColumnType("TEXT");

                    b.Property<string>("Rubro")
                        .HasColumnType("TEXT");

                    b.Property<int?>("TarjetaCreditoTarjetaId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TarjetaId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ConsumoId");

                    b.HasIndex("TarjetaCreditoTarjetaId");

                    b.HasIndex("TarjetaId");

                    b.ToTable("Consumos");
                });

            modelBuilder.Entity("Entidades.Descuento", b =>
                {
                    b.Property<int>("DescuentoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Activo")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Acumulable")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Banco")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Emisor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MontoFijo")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MontoMinimo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Porcentaje")
                        .HasColumnType("TEXT");

                    b.Property<string>("Rubro")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TopeReintegro")
                        .HasColumnType("TEXT");

                    b.HasKey("DescuentoId");

                    b.ToTable("Descuentos");

                    b.HasData(
                        new
                        {
                            DescuentoId = 1,
                            Activo = true,
                            Acumulable = false,
                            Banco = "Banco Santander",
                            Codigo = "SUPER30",
                            Descripcion = "30% los miércoles en supermercados",
                            Emisor = "VISA",
                            FechaFin = new DateTime(2025, 6, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaInicio = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MontoFijo = 0m,
                            MontoMinimo = 0m,
                            Nombre = "Miércoles de descuentos",
                            Porcentaje = 30m,
                            Rubro = "Supermercados",
                            Tipo = "Porcentual",
                            TopeReintegro = 3000m
                        },
                        new
                        {
                            DescuentoId = 2,
                            Activo = true,
                            Acumulable = false,
                            Banco = "Banco BBVA",
                            Codigo = "REST2X1",
                            Descripcion = "2x1 en restaurantes adheridos",
                            Emisor = "American Express",
                            FechaFin = new DateTime(2025, 4, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaInicio = new DateTime(2025, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MontoFijo = 0m,
                            MontoMinimo = 0m,
                            Nombre = "2x1 en Restaurantes",
                            Porcentaje = 50m,
                            Rubro = "Restaurantes",
                            Tipo = "Porcentual",
                            TopeReintegro = 1500m
                        },
                        new
                        {
                            DescuentoId = 3,
                            Activo = true,
                            Acumulable = true,
                            Banco = "Banco Nación",
                            Codigo = "FARM15",
                            Descripcion = "15% todos los días en farmacias",
                            Emisor = "Mastercard",
                            FechaFin = new DateTime(2025, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaInicio = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MontoFijo = 0m,
                            MontoMinimo = 0m,
                            Nombre = "Descuento en Farmacias",
                            Porcentaje = 15m,
                            Rubro = "Farmacias",
                            Tipo = "Porcentual",
                            TopeReintegro = 1000m
                        });
                });

            modelBuilder.Entity("Entidades.Persona", b =>
                {
                    b.Property<int>("PersonaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DNI")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("PersonaId");

                    b.ToTable("Personas");

                    b.HasData(
                        new
                        {
                            PersonaId = 1,
                            Apellido = "Colombano",
                            DNI = "44555998",
                            Nombre = "Gabriel"
                        },
                        new
                        {
                            PersonaId = 2,
                            Apellido = "Llanos",
                            DNI = "12355666",
                            Nombre = "Matias"
                        },
                        new
                        {
                            PersonaId = 3,
                            Apellido = "Gallegos",
                            DNI = "12577889",
                            Nombre = "Laureano"
                        },
                        new
                        {
                            PersonaId = 4,
                            Apellido = "Lopez",
                            DNI = "13344895",
                            Nombre = "Pedro"
                        });
                });

            modelBuilder.Entity("Entidades.Tarjeta", b =>
                {
                    b.Property<int>("TarjetaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Alias")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Banco")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EntidadEmisora")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaVencimiento")
                        .HasColumnType("TEXT");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PersonaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TipoTarjeta")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("TarjetaId");

                    b.HasIndex("PersonaId");

                    b.ToTable("Tarjetas");

                    b.HasDiscriminator<string>("TipoTarjeta").HasValue("Tarjeta");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Entidades.TarjetaCredito", b =>
                {
                    b.HasBaseType("Entidades.Tarjeta");

                    b.Property<decimal>("Disponible")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsExtension")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Limite")
                        .HasColumnType("TEXT");

                    b.Property<int>("TenedorId")
                        .HasColumnType("INTEGER");

                    b.HasIndex("TenedorId");

                    b.HasDiscriminator().HasValue("Credito");

                    b.HasData(
                        new
                        {
                            TarjetaId = 2,
                            Alias = "Macro Mati",
                            Banco = "Banco Macro",
                            EntidadEmisora = "Mastercard",
                            FechaVencimiento = new DateTime(2028, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Numero = "5555666677778888",
                            PersonaId = 2,
                            Disponible = 500000m,
                            IsExtension = true,
                            Limite = 1000000m,
                            TenedorId = 2
                        });
                });

            modelBuilder.Entity("Entidades.TarjetaDebito", b =>
                {
                    b.HasBaseType("Entidades.Tarjeta");

                    b.Property<decimal>("Saldo")
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue("Debito");

                    b.HasData(
                        new
                        {
                            TarjetaId = 1,
                            Alias = "BBVA Mati",
                            Banco = "Banco BBVA",
                            EntidadEmisora = "VISA",
                            FechaVencimiento = new DateTime(2026, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Numero = "1111222233334444",
                            PersonaId = 2,
                            Saldo = 100000m
                        });
                });

            modelBuilder.Entity("ConsumoDescuento", b =>
                {
                    b.HasOne("Entidades.Consumo", null)
                        .WithMany()
                        .HasForeignKey("ConsumoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entidades.Descuento", null)
                        .WithMany()
                        .HasForeignKey("DescuentosAplicadosDescuentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Entidades.Acreditacion", b =>
                {
                    b.HasOne("Entidades.TarjetaCredito", null)
                        .WithMany("Acreditaciones")
                        .HasForeignKey("TarjetaCreditoTarjetaId");

                    b.HasOne("Entidades.Tarjeta", "Tarjeta")
                        .WithMany()
                        .HasForeignKey("TarjetaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tarjeta");
                });

            modelBuilder.Entity("Entidades.Consumo", b =>
                {
                    b.HasOne("Entidades.TarjetaCredito", null)
                        .WithMany("Consumos")
                        .HasForeignKey("TarjetaCreditoTarjetaId");

                    b.HasOne("Entidades.Tarjeta", "Tarjeta")
                        .WithMany()
                        .HasForeignKey("TarjetaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tarjeta");
                });

            modelBuilder.Entity("Entidades.Tarjeta", b =>
                {
                    b.HasOne("Entidades.Persona", "Titular")
                        .WithMany("Tarjetas")
                        .HasForeignKey("PersonaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Titular");
                });

            modelBuilder.Entity("Entidades.TarjetaCredito", b =>
                {
                    b.HasOne("Entidades.Persona", "Tenedor")
                        .WithMany()
                        .HasForeignKey("TenedorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenedor");
                });

            modelBuilder.Entity("Entidades.Persona", b =>
                {
                    b.Navigation("Tarjetas");
                });

            modelBuilder.Entity("Entidades.TarjetaCredito", b =>
                {
                    b.Navigation("Acreditaciones");

                    b.Navigation("Consumos");
                });
#pragma warning restore 612, 618
        }
    }
}
