// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Modelo;

#nullable disable

namespace Modelo.Migrations
{
    [DbContext(typeof(Context))]
    partial class ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.0");

            modelBuilder.Entity("ConsumoDescuento", b =>
                {
                    b.Property<int>("ConsumoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DescuentosAplicadosDescuentoId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ConsumoId", "DescuentosAplicadosDescuentoId");

                    b.HasIndex("DescuentosAplicadosDescuentoId");

                    b.ToTable("ConsumoDescuento");
                });

            modelBuilder.Entity("Entidades.Acreditacion", b =>
                {
                    b.Property<int>("AcreditacionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<string>("MedioDePago")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Monto")
                        .HasColumnType("TEXT");

                    b.Property<int?>("TarjetaCreditoTarjetaId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TarjetaId")
                        .HasColumnType("INTEGER");

                    b.HasKey("AcreditacionId");

                    b.HasIndex("TarjetaCreditoTarjetaId");

                    b.HasIndex("TarjetaId");

                    b.ToTable("Acreditaciones");
                });

            modelBuilder.Entity("Entidades.Consumo", b =>
                {
                    b.Property<int>("ConsumoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Comercio")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("EsRecurrente")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<string>("Hora")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Moneda")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Monto")
                        .HasColumnType("TEXT");

                    b.Property<string>("Rubro")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("TarjetaCreditoTarjetaId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TarjetaId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ConsumoId");

                    b.HasIndex("TarjetaCreditoTarjetaId");

                    b.HasIndex("TarjetaId");

                    b.ToTable("Consumos");
                });

            modelBuilder.Entity("Entidades.Descuento", b =>
                {
                    b.Property<int>("DescuentoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Activo")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Acumulable")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Banco")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Emisor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MontoFijo")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MontoMinimo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Porcentaje")
                        .HasColumnType("TEXT");

                    b.Property<string>("Rubro")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TopeReintegro")
                        .HasColumnType("TEXT");

                    b.HasKey("DescuentoId");

                    b.ToTable("Descuentos");

                    b.HasData(
                        new
                        {
                            DescuentoId = 1,
                            Activo = true,
                            Acumulable = true,
                            Banco = "Todos",
                            Codigo = "DESC10",
                            Descripcion = "Descuento del 10% en compras",
                            Emisor = "Sistema",
                            FechaFin = new DateTime(2025, 8, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaInicio = new DateTime(2025, 7, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MontoFijo = 0m,
                            MontoMinimo = 100m,
                            Nombre = "Descuento 10%",
                            Porcentaje = 10m,
                            Rubro = "Todos",
                            Tipo = "Porcentual",
                            TopeReintegro = 1000m
                        },
                        new
                        {
                            DescuentoId = 2,
                            Activo = true,
                            Acumulable = false,
                            Banco = "Banco Nación",
                            Codigo = "DESC20",
                            Descripcion = "Descuento del 20% en compras",
                            Emisor = "Sistema",
                            FechaFin = new DateTime(2025, 9, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaInicio = new DateTime(2025, 7, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MontoFijo = 0m,
                            MontoMinimo = 500m,
                            Nombre = "Descuento 20%",
                            Porcentaje = 20m,
                            Rubro = "Alimentación",
                            Tipo = "Porcentual",
                            TopeReintegro = 2000m
                        },
                        new
                        {
                            DescuentoId = 3,
                            Activo = true,
                            Acumulable = true,
                            Banco = "Todos",
                            Codigo = "DESC5",
                            Descripcion = "Descuento del 5% en compras",
                            Emisor = "Sistema",
                            FechaFin = new DateTime(2025, 10, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaInicio = new DateTime(2025, 7, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MontoFijo = 0m,
                            MontoMinimo = 50m,
                            Nombre = "Descuento 5%",
                            Porcentaje = 5m,
                            Rubro = "Todos",
                            Tipo = "Porcentual",
                            TopeReintegro = 500m
                        });
                });

            modelBuilder.Entity("Entidades.Persona", b =>
                {
                    b.Property<int>("PersonaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DNI")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("PersonaId");

                    b.ToTable("Personas");

                    b.HasData(
                        new
                        {
                            PersonaId = 1,
                            Apellido = "Colombano",
                            DNI = "44555998",
                            Nombre = "Gabriel"
                        },
                        new
                        {
                            PersonaId = 2,
                            Apellido = "Llanos",
                            DNI = "12355666",
                            Nombre = "Matias"
                        },
                        new
                        {
                            PersonaId = 3,
                            Apellido = "Gallegos",
                            DNI = "12577889",
                            Nombre = "Laureano"
                        },
                        new
                        {
                            PersonaId = 4,
                            Apellido = "Lopez",
                            DNI = "13344895",
                            Nombre = "Pedro"
                        });
                });

            modelBuilder.Entity("Entidades.Tarjeta", b =>
                {
                    b.Property<int>("TarjetaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Alias")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Banco")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EntidadEmisora")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaVencimiento")
                        .HasColumnType("TEXT");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PersonaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TipoTarjeta")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("TarjetaId");

                    b.HasIndex("PersonaId");

                    b.ToTable("Tarjetas");

                    b.HasDiscriminator<string>("TipoTarjeta").HasValue("Tarjeta");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Entidades.TarjetaCredito", b =>
                {
                    b.HasBaseType("Entidades.Tarjeta");

                    b.Property<decimal>("Disponible")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsExtension")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Limite")
                        .HasColumnType("TEXT");

                    b.Property<int>("TenedorPersonaId")
                        .HasColumnType("INTEGER");

                    b.HasIndex("TenedorPersonaId");

                    b.HasDiscriminator().HasValue("Credito");
                });

            modelBuilder.Entity("Entidades.TarjetaDebito", b =>
                {
                    b.HasBaseType("Entidades.Tarjeta");

                    b.Property<decimal>("Saldo")
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue("Debito");
                });

            modelBuilder.Entity("ConsumoDescuento", b =>
                {
                    b.HasOne("Entidades.Consumo", null)
                        .WithMany()
                        .HasForeignKey("ConsumoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entidades.Descuento", null)
                        .WithMany()
                        .HasForeignKey("DescuentosAplicadosDescuentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Entidades.Acreditacion", b =>
                {
                    b.HasOne("Entidades.TarjetaCredito", null)
                        .WithMany("Acreditaciones")
                        .HasForeignKey("TarjetaCreditoTarjetaId");

                    b.HasOne("Entidades.Tarjeta", "Tarjeta")
                        .WithMany()
                        .HasForeignKey("TarjetaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tarjeta");
                });

            modelBuilder.Entity("Entidades.Consumo", b =>
                {
                    b.HasOne("Entidades.TarjetaCredito", null)
                        .WithMany("Consumos")
                        .HasForeignKey("TarjetaCreditoTarjetaId");

                    b.HasOne("Entidades.Tarjeta", "Tarjeta")
                        .WithMany()
                        .HasForeignKey("TarjetaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tarjeta");
                });

            modelBuilder.Entity("Entidades.Tarjeta", b =>
                {
                    b.HasOne("Entidades.Persona", "Titular")
                        .WithMany("Tarjetas")
                        .HasForeignKey("PersonaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Titular");
                });

            modelBuilder.Entity("Entidades.TarjetaCredito", b =>
                {
                    b.HasOne("Entidades.Persona", "Tenedor")
                        .WithMany()
                        .HasForeignKey("TenedorPersonaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenedor");
                });

            modelBuilder.Entity("Entidades.Persona", b =>
                {
                    b.Navigation("Tarjetas");
                });

            modelBuilder.Entity("Entidades.TarjetaCredito", b =>
                {
                    b.Navigation("Acreditaciones");

                    b.Navigation("Consumos");
                });
#pragma warning restore 612, 618
        }
    }
}
